jobs:
  - job: UiAutomator2ServerCI
    pool:
      vmImage: macOS-10.15
    variables:
      CI: true
      TERM: dumb
      ANDROID_SDK_VERSION: 28
      ANDROID_AVD: test
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 10.x
    - script: npm install
      displayName: Install Node dependencies
    - script: bash ci-jobs/scripts/start-emulator.sh
      displayName: Create and run Emulator
    - script: ./gradlew connectedE2eTestDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=io.appium.uiautomator2.unittest.test.ActionsCommandsTest -Pandroid.testInstrumentationRunnerArguments.notAnnotation=io.appium.uiautomator2.unittest.test.internal.SkipHeadlessDevices
      displayName: Run Gradle Tests
    - bash: adb logcat -d
      condition: or(succeeded(), failed())
      displayName: 'logcat'
